export default [
    'propagation of totalitarian regimes',
    'hate speech',
    'racism',
    'xenophobia',
    'homophobia',
    'transphobia',
    'enbyphobia',
    'queerphobia',
    'queer exclusionism',
    'misogyny',
    'harassment',
    'impersonation',
    'child pornography',
    'unlawful conduct',
    'misinformation',
    'sharing of someone else\'s personal data',
    'spam',
    'advertisement',
    'copyright or trademark violations',
];
